From ollama/ollama
WORKDIR /workspace
#COPY ./llama2 /models/llama3.2
#COPY ./phi3 /models/phi3
#CMD ["ollama", "serve"]
#SHELL ["ollama", "serve"]
SHELL ["ollama", "run","llama3.2"]
SHELL ["ollama", "run","Llama-3-Taiwan-70B-Instruct"]
#RUN ollama run llama3.2
#RUN ollama run Llama-3-Taiwan-70B-Instruct
#CMD ["ollama", "run" ,"Llama-3-Taiwan-70B-Instruct"]
#EXPOSE 11434
#CMD ["ollama","serve"]
#CMD ["bash"]


